services:
  after_api_service:
    env_file:
      - .env
    build:
      context: .
    image: after/after_service:latest
    container_name: after_api_service
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - after_db_local
    volumes:
      - ./api:/app/api
      - ./alembic/versions:/app/alembic/versions
    networks:
      - after_network

  after_db_local:
    image: postgres:13
    container_name: after_db_local
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - after_postgres_data:/var/lib/postgresql/data
    networks:
      - after_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U after -d after_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  after_postgres_data:
    driver: local

networks:
  after_network:
    driver: bridge
